GET http://localhost:9200/aircrafts/_search
Content-Type: application/json

{
  "query": {
    "bool": {
      "must": [
        { "match": { "manufacturer": "Airbus" } },
        { "term": { "status": "ACTIVE" } }
      ],
      "must_not": {
        "range": { "delivery_date": { "gte": "2010-01-01" } }
      }
    }
  }
}
